CC=clang
# no-slp-vectorize to prevent autovectorization of the benchmark;
# note that more needs to be done to prevent benchmarking effects
# here.
CFLAGS=-Wall -O3 -g -fno-slp-vectorize
all: ilog
clean:
	/bin/rm -rf ilog
